### ISSUE TITLE
Hosting package on Anaconda conda-forge channel

### ISSUE THREAD

**Issue by tomvothecoder** [your-tools/tbump#130]
Just a suggestion, but I commonly work with Anaconda and use a `.yml` file to build an environment (using `conda-forge` channel to install dependencies). The only package that I have to list under the pip section  is `tbump`. It would be nice of `tbump` was also hosted on `conda-forge`. This might also help the package gain more users via Anaconda.

Thanks!

**Comment by umonaca** [comment]
@dmerejkowsky I am one of the feedstock maintainers for the conda-forge and I am willing to create a recipe for you. I would want to add you as a maintainer of the recipe, so that you can edit it yourself.

**Comment by dmerejkowsky** [comment]
@umonaca That's very kind of you, thanks. Feel free to create the recipe and add me as maintainer.

**Comment by umonaca** [comment]
It is available on Anaconda Cloud yesterday. You can install with something like `mamba install -c conda-forge tbump`.
