### ISSUE TITLE
tbump should be able to make signed tag

### ISSUE THREAD

**Issue by AlexandreBossard** [your-tools/tbump#133]
Pretty much what's in the title. I believe it's not possible to do this, or maybe I missed something?

**Comment by dmerejkowsky** [comment]
Well, you can do something like:

```
tbump --no-tag NEW_VERSION
git tag -m v<NEW_VERSION> --sign
````
But this looks like a legit request. We could add more sections in the `[git]` section, like this:

```toml
[git]
sign = true
```
