### ISSUE TITLE
Error: Repository is dirty

### ISSUE THREAD

**Issue by iccicci** [your-tools/tbump#135]
Hi all, is there a way to instruct `tbump` to ignore the error in topic and proceed?
It would be so useful moreover in conjunction with `--only-patch`.

Thank you,
iCC

**Comment by dmerejkowsky** [comment]
Hum, I tried it and it looks to me `tbump` already skips the "check for a dirty git repo" step if `--only-patch` is used.

Which version of tbump are you using ?

**Comment by dmerejkowsky** [comment]
Closing due to lack of response
