### ISSUE TITLE
Include option to disable --atomic on push

### ISSUE THREAD

**Issue by mlongtin0** [your-tools/tbump#161]
Some git servers don't support `git push --atomic`. Looking at you, Azure DevOps.

It would be nice if there was an option to disable push or --atomic in the config file.

**Comment by dmerejkowsky** [comment]
Should not be too hard to implement. Do you want to try and give it a go ?

**Comment by dmerejkowsky** [comment]
Let's close this - #167 is merged :)

**Comment by Tobotimus** [comment]
Hi! Is there any chance for this to be released in the near future? Unfortunately, without this feature, using tbump with a shitty Git host means you must always either do `--no-push` or `--only-patch`.

Thanks :)

**Comment by dmerejkowsky** [comment]
And it's merged :)
