### ISSUE TITLE
Thoughts about testing ...

### ISSUE THREAD

**Issue by dmerejkowsky** [your-tools/tbump#165]
Since #164 we now has `push_no_atomic` in `tests/project/` which is probably not what we want - after all, most devs were fine with the atomic push so far, so now our tests no longer reflect the majoriy of use case.

In insight, it's obvious we should not have duplicated the `tbump.toml` and test projects back when support for `pyproject.toml` was merged.

So we need to think of a way to test tbump with various configuration files, without duplicating them.

Also, currently we don't really check if `--atomic` is used during push, because we only check that the tag was created and the branch was updated.

I think this should be fixed before we make a new release - bad tests might cause bugs to occur (among other things)

**Comment by dmerejkowsky** [comment]
What do you think, @minrk ?

**Comment by mlongtin0** [comment]
Oh yeah. I put it in one project, but not the other. But that may conflict with something else being tested.

**Comment by dmerejkowsky** [comment]
So ... I went ahead and did that - and I found a bug ;)

If nothing is set in the config and use use `--no-atomitc-push`, you still end up calling `git push` with the `--atomic` option

(see failing test in the `improve-tests` branch)


Problem is we call `set_config` in the `GitBumper` after `__init__`  so the config file takes precedence over the command line (and we want the opposite)

All of this makes me wonder why we need both the config file and the command line ... Maybe we should configure the push only in the config file ?

**Comment by mlongtin0** [comment]
It should probably be config only. I was following your lead with option and config.

**Comment by dmerejkowsky** [comment]
OK. I've opened #166
