### ISSUE TITLE
[6.11.0] --config option fails when given a relative path

### ISSUE THREAD

**Issue by theodelrieu** [your-tools/tbump#168]
Hello,

I just bumped tbump to version 6.11.0 on macOS, and got an error with the following command:

`tbump --config ./tbump-sdk.toml 0.10.1-alpha13 --only-patch --non-interactive`

>ValueError: 'tbump-sdk.toml' is not in the subpath of '/Users/theo/sdk-ios' OR one path is relative and the other is absolute.

Seems weird, as `tbump` is the one retrieving the said absolute path. I worked around it by providing `--cwd=.`

**Comment by awerner** [comment]
6.10. seems also to be affected for me. Python 3.9.
